<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.2.0.352
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Отправка Форма Домашняя',
	'heading' => 'Отправка новой формы',
	'success_redirect' => '../index.html',
	'resources' => array(
		'checkbox_checked' => 'Отмечено',
		'checkbox_unchecked' => 'Флажок не установлен',
		'submitted_from' => 'Формы, отправленные с веб-сайта: %s',
		'submitted_by' => 'IP-адрес посетителя: %s',
		'too_many_submissions' => 'Недопустимо высокое количество отправок с этого IP-адреса за последнее время',
		'failed_to_send_email' => 'Не удалось отправить сообщение эл. почты',
		'invalid_reCAPTCHA_private_key' => 'Недействительный закрытый ключ reCAPTCHA.',
		'invalid_field_type' => 'Неизвестный тип поля \'%s\'.',
		'invalid_form_config' => 'Недопустимая конфигурация поля \"%s\".',
		'unknown_method' => 'Неизвестный метод запроса сервера'
	),
	'email' => array(
		'from' => 'AtMte@mail.ru',
		'to' => 'AtMte@mail.ru'
	),
	'fields' => array(
		'custom_U1332' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Ваше Имя',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Ваше Имя\' не может быть пустым.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Электронная почта',
			'required' => false,
			'errors' => array(
				'format' => 'Поле \'Электронная почта\' содержит недействительное сообщение эл. почты.'
			)
		),
		'custom_U1350' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Сообщение',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U1354' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Мобильный телефон',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Мобильный телефон\' не может быть пустым.'
			)
		),
		'custom_U1358' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Укажите удобную  для Вас дату и время',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Укажите удобную  для Вас дату и время\' не может быть пустым.'
			)
		),
		'custom_U1326' => array(
			'order' => 4,
			'type' => 'checkbox',
			'label' => 'Шугаринг',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Шугаринг\' не может быть пустым.'
			)
		),
		'custom_U1346' => array(
			'order' => 5,
			'type' => 'checkbox',
			'label' => 'Ногтевой сервис',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Ногтевой сервис\' не может быть пустым.'
			)
		),
		'custom_U1342' => array(
			'order' => 6,
			'type' => 'checkbox',
			'label' => 'Приобретение натуральной косметики',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Приобретение натуральной косметики\' не может быть пустым.'
			)
		)
	)
);

process_form($form);
?>
